# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:13
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('links', '0002_auto_20170613_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
