# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='book',
            field=models.ManyToManyField(to='links.Book'),
        ),
        migrations.AddField(
            model_name='link',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
