# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20170613_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='book',
            new_name='books',
        ),
    ]
