# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20170614_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
