# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 07:34
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20170616_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='og_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
