# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backend',
            field=models.CharField(default='linkbook', max_length=10),
        ),
    ]
