# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170623_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(default='http://i.imgur.com/xz4vNF9.png'),
        ),
    ]
