# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_social_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_id',
        ),
    ]
