# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170623_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backend',
            field=models.CharField(default='linkbook', max_length=20),
        ),
    ]
