# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_link_og_data'),
        ('authentication', '0006_auto_20170625_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upvoted_links',
            field=models.ManyToManyField(to='links.Link'),
        ),
    ]
