# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_upvoted_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upvoted_links',
            field=models.ManyToManyField(blank=True, to='links.Link'),
        ),
    ]
