# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20170709_0708'),
        ('authentication', '0010_auto_20170708_1621'),
    ]

    operations = [
    ]
